services:
  app:
    build:
      context: '.'
      dockerfile: 'Dockerfile.dev'
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_API_KEY: "${GITHUB_API_KEY}"
    env_file:
      - ".env"
    volumes:
      - .:/app
    ports:
      - 8080:80
    networks:
      - kafka

networks:
  kafka:
    name: kafka
    external: true
